imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@BundlesOptionBundle/Resources/config/admin.yml" }
# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        googleApiKey: "%google_api%"
        googleAnalytics: "%google_analytics%"
        googleTagManager: "%google_tag_manager%"
        friends: "@friend_manager"
        lastConnections: "@last_connection_manager"
        messageManager: "@message_manager"
        notificationManager: "@notification_manager"
        SiteManagement: "@SiteManagement"
        api_url: "%api_url%"
        api_token: "%api_token%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            numeric_functions:
                acos: DoctrineExtensions\Query\Mysql\Acos
                cos: DoctrineExtensions\Query\Mysql\Cos
                sin: DoctrineExtensions\Query\Mysql\Sin
            string_functions:
                radians: DoctrineExtensions\Query\Mysql\Radians

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_username%"
    password:   "%mailer_password%"
    auth_mode:  "%mailer_auth_mode%"
    port:       "%mailer_port%"
    sender_address: "%mailer_from%"
    encryption: "%mailer_encryption%"

# FosUser Configuration
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Bundles\UserBundle\Entity\User
    service:
        mailer: bundles_user.mailer
    registration:
        confirmation:
            enabled: true
    from_email:
        address:        "%mailer_from%"
        sender_name:    Manavao
    resetting:
        email:
            template:   '@FOSUser/Resetting/email.txt.twig'

# MultiLanguage
jms_i18n_routing:
    default_locale: fr
    locales: [fr, en, es, ca]
    strategy: prefix_except_default

a2lix_translation_form:
    locale_provider: default
    locales: [fr, en, es, ca]
    default_locale: fr
    required_locales: [fr, en]
    templating: "A2lixTranslationFormBundle::default.html.twig"
