security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER, ROLE_MEMBER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
                # if you are using Symfony < 2.8, use the following config instead:
                # csrf_provider: form.csrf_provider
#                default_target_path: /profile

            logout:
                path: fos_user_security_logout
                target: homepage
            anonymous:    true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/(en|fr|es|ca)/registration, role: ROLE_USER }
        - { path: ^/registration, role: ROLE_USER }
        - { path: ^/profile/, role: ROLE_MEMBER }
        - { path: ^/(en|fr|es|ca)/profile/, role: ROLE_MEMBER }
        - { path: ^/profile, role: ROLE_USER }
        - { path: ^/(en|fr|es|ca)/profile, role: ROLE_USER }
        