<?php

namespace Bundles\OptionBundle\DataFixtures\ORM;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\Persistence\ObjectManager;

use Bundles\OptionBundle\Entity\Category;
use Bundles\OptionBundle\Entity\Industry;
use Bundles\OptionBundle\Entity\Zone;
use Bundles\OptionBundle\Entity\InterestedIn;
use Bundles\OptionBundle\Entity\ProjectType;
use Bundles\OptionBundle\Entity\PostCategory;
use Bundles\OptionBundle\Entity\AuthorType;
use Bundles\OptionBundle\Entity\Skill;
use Bundles\OptionBundle\Entity\EventType;
use Bundles\OptionBundle\Entity\BusinessArea;
use Bundles\OptionBundle\Entity\OrganisationSize;
use Bundles\OptionBundle\Entity\OrganisationType;
use Bundles\OptionBundle\Entity\Department;
use Bundles\OptionBundle\Entity\Language;
use Bundles\OptionBundle\Entity\Clients;

class LoadOptions extends AbstractFixture
{
    public function load(ObjectManager $manager)
    {
        /*
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            'Association',
            'Business club or network',
            'Economic development organisation',
            'Entrepreneur (not established))',
            'Financial organisation',
            'International organisation',
            'Large company',
            'Incubator & business park',
            'Medias & websites',
            'Other economic stakeholder',
            'Professional Union',
            'Other public organisation',
            'SME',
            'Start-up',
            'Chamber of commerce & agriculture',
            'University & High school',
            'European institution',
            'Local authority',
            'Governement administration',
            'Non caritative organisation',
            'Investment fund',
            'Training organisation',
            'research center',
            'Technopole & innovation center',
            'Self employed & Auto-entrepreneurs',
        ];
        $data['fr'] = [
            'Association',
            'Réseau & club d\'affaires',
            'Agence ou service en charge du développement économique',
            'Société en création',
            'Institution financière & banque',
            'Organisation internationale',
            'Grande entreprise',
            'Incubateur & pépinière d\'entreprises',
            'Médias & sites Internet',
            'Autre acteur économique',
            'Fédération professionnelle',
            'Autre organisme public',
            'Petite ou Moyenne entreprise',
            'Start-up',
            'Chambres de commerce, métiers ou agriculture',
            'Université & Ecoles supérieures',
            'Institution de l\'Union européenne',
            'Collectivités territoriales',
            'Administration de l\'Etat',
            'ONG',
            'Fonds d\'investissement',
            'Organisme de formation',
            'Centre de recherche & laboratoire scientifique',
            'Pôles technologiques et centres d\'innovation',
            'Auto-entrepreneur',
        ];
        $this->fillOption(Category::class, $this->arrayMix($data), $manager);
        
        
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            'Accounting',
            'Airlines/Aviation',
            'Alternative Dispute Resolution',
            'Alternative Medicine',
            'Animation',
            'Apparel & Fashion',
            'Architecture & Planning',
            'Arts and Crafts',
            'Automotive',
            'Aviation & Aerospace',
            'Banking',
            'Biotechnology',
            'Broadcast Media',
            'Building Materials',
            'Business Supplies and Equipment',
            'Capital Markets',
            'Chemicals',
            'Civic & Social Organization',
            'Civil Engineering',
            'Commercial Real Estate',
            'Computer & Network Security',
            'Computer Games',
            'Computer Hardware',
            'Computer Networking',
            'Computer Software',
            'Construction',
            'Consumer Electronics',
            'Consumer Goods',
            'Consumer Services',
            'Cosmetics',
            'Dairy',
            'Defense & Space',
            'Design',
            'Education Management',
            'E-Learning',
            'Electrical/Electronic Manufacturing',
            'Entertainment',
            'Environmental Services',
            'Events Services',
            'Executive Office',
            'Facilities Services',
            'Farming',
            'Financial Services',
            'Fine Art',
            'Fishery',
            'Food & Beverages',
            'Food Production',
            'Fund-Raising',
            'Furniture',
            'Gambling & Casinos',
            'Glass, Ceramics & Concrete',
            'Government Administration',
            'Government Relations',
            'Graphic Design',
            'Health, Wellness and Fitness',
            'Higher Education',
            'Hospital & Health Care',
            'Hospitality',
            'Human Resources',
            'Import and Export',
            'Individual & Family Services',
            'Industrial Automation',
            'Information Services',
            'Information Technology and Services',
            'Insurance',
            'International Affairs',
            'International Trade and Development',
            'Internet',
            'Investment Banking',
            'Investment Management',
            'Judiciary',
            'Law Enforcement',
            'Law Practice',
            'Legal Services',
            'Legislative Office',
            'Leisure, Travel & Tourism',
            'Libraries',
            'Logistics and Supply Chain',
            'Luxury Goods & Jewelry',
            'Machinery',
            'Management Consulting',
            'Maritime',
            'Marketing and Advertising',
            'Market Research',
            'Mechanical or Industrial Engineering',
            'Media Production',
            'Medical Devices',
            'Medical Practice',
            'Mental Health Care',
            'Military',
            'Mining & Metals',
            'Motion Pictures and Film',
            'Museums and Institutions',
            'Music',
            'Nanotechnology',
            'Newspapers',
            'Nonprofit Organization Management',
            'Oil & Energy',
            'Online Media',
            'Outsourcing/Offshoring',
            'Package/Freight Delivery',
            'Packaging and Containers',
            'Paper & Forest Products',
            'Performing Arts',
            'Pharmaceuticals',
            'Philanthropy',
            'Photography',
            'Plastics',
            'Political Organization',
            'Primary/Secondary Education',
            'Printing',
            'Professional Training & Coaching',
            'Program Development',
            'Public Policy',
            'Public Relations and Communications',
            'Public Safety',
            'Publishing',
            'Railroad Manufacture',
            'Ranching',
            'Real Estate',
            'Recreational Facilities and Services',
            'Religious Institutions',
            'Renewables & Environment',
            'Research',
            'Restaurants',
            'Retail',
            'Security and Investigations',
            'Semiconductors',
            'Shipbuilding',
            'Sporting Goods',
            'Sports',
            'Staffing and Recruiting',
            'Supermarkets',
            'Telecommunications',
            'Textiles',
            'Think Tanks',
            'Tobacco',
            'Translation and Localization',
            'Transportation/Trucking/Railroad',
            'Utilities',
            'Venture Capital & Private Equity',
            'Veterinary',
            'Warehousing',
            'Wholesale',
            'Wine and Spirits',
            'Wireless',
            'Writing and Editing',
        ];
        $data['fr'] = [
            "Administration publique",
            "Administration scolaire et universitaire",
            "Aéronautique et aérospatiale",
            "Affaires étrangères",
            "Agriculture",
            "Agro-alimentaire",
            "Architecture et urbanisme",
            "Armée",
            "Articles de luxe et bijouterie",
            "Articles de sport",
            "Arts",
            "Arts et artisanat",
            "Arts vivants",
            "Associations et organisations sociales et syndicales",
            "Assurances",
            "Automatismes industriels",
            "Avocats",
            "Banques",
            "Bibliothèques",
            "Biens de consommation",
            "Biens et équipements pour les entreprises",
            "Biotechnologie",
            "Capital-risque et fonds LBO",
            "Centres de recherches",
            "Chantiers navals",
            "Chimie",
            "Collectivités publiques et territoriales",
            "Commerce de détail",
            "Commerce de gros",
            "Commerce et développement international",
            "Compagnie aérienne/Aviation",
            "Comptabilité",
            "Confection et mode",
            "Conseil en management",
            "Construction",
            "Contenus rédactionnels",
            "Cosmétiques",
            "Défense et espace",
            "Design",
            "Design graphique",
            "Divertissements",
            "Édition",
            "Élaboration de programmes",
            "Élevage",
            "Emballages et conteneurs",
            "Enseignement supérieur",
            "Entreposage, stockage",
            "Environnement et énergies renouvelables",
            "Équipements collectifs",
            "Équipements et services de loisirs",
            "Équipements ferroviaires",
            "Équipements médicaux",
            "Études/recherche",
            "Études de marché",
            "Externalisation/délocalisation",
            "Films d’animation",
            "Formation à distance",
            "Formation primaire/secondaire",
            "Formation professionnelle et coaching",
            "Génie civil",
            "Gestion de portefeuilles",
            "Gestion des associations et fondations",
            "Grande distribution",
            "Hôpitaux et centres de soins",
            "Hôtellerie et hébergement",
            "Humanitaire",
            "Immobilier",
            "Immobilier commercial",
            "Import et export",
            "Imprimerie, reproduction",
            "Industrie automobile",
            "Industrie bois et papiers",
            "Industrie composants électriques/électroniques",
            "Industrie du cinéma",
            "Industrie pharmaceutique",
            "Industrie textile",
            "Ingénierie du mécénat",
            "Ingénierie mécanique ou industrielle",
            "Institutions judiciaires",
            "Institutions religieuses",
            "Internet",
            "Jeux d’argent et casinos",
            "Jeux électroniques",
            "Logiciels informatiques",
            "Logistique et chaîne d’approvisionnement",
            "Loisirs, voyages et tourisme",
            "Machines et équipements",
            "Mandat législatif",
            "Mandat politique",
            "Marchés des capitaux",
            "Marketing et publicité",
            "Matériaux de construction",
            "Matériel informatique",
            "Matières premières",
            "Médecines alternatives",
            "Médias en ligne",
            "Médias radio et télédiffusés",
            "Messageries et fret",
            "Meubles",
            "Mines et métaux",
            "Musées et institutions culturelles",
            "Musique",
            "Nanotechnologies",
            "Organisation d’événements",
            "Parti politique",
            "Pêche",
            "Pétrole et énergie",
            "Photographie",
            "Plastiques",
            "Police/gendarmerie",
            "Politiques publiques",
            "Presse écrite",
            "Production audiovisuelle",
            "Produits électroniques grand public",
            "Professions médicales",
            "Recrutement",
            "Règlement extrajudiciaire de conflits",
            "Relations publiques et communication",
            "Réseaux informatiques",
            "Ressources humaines",
            "Restaurants",
            "Restauration collective",
            "Santé, forme et bien-être",
            "Secteur laitier",
            "Secteur médico-psychologique",
            "Sécurité civile",
            "Sécurité et enquêtes",
            "Sécurité informatique et des réseaux",
            "Semi-conducteurs",
            "Services à la personne",
            "Services aux consommateurs",
            "Services d’information",
            "Services d’investissement",
            "Services financiers",
            "Services juridiques",
            "Services pour l’environnement",
            "Sports",
            "Tabac",
            "Technologies et services de l’information",
            "Technologies sans fil",
            "Télécommunications",
            "Traduction et adaptation",
            "Transports maritimes",
            "Transports routiers et ferroviaires",
            "Verres, céramiques et ciments",
            "Vétérinaire",
            "Vins et spiritueux",

        ];
        $this->fillOption(Industry::class, $this->arrayMix($data), $manager);
        
        
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            "Local",
            "Regional",
            "National ",
            "Continental",
            "Global",

        ];
        $data['fr'] = [
            "Ville ",
            "Région",
            "Pays",
            "Continent",
            "Global",

        ];
        $this->fillOption(Zone::class, $this->arrayMix($data), $manager);
      
        
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            "Develop your business network",
            "Find clients or suppliers or partners",
            "Promote your organisation or your territory",
            "Ensure a business intelligence",
            "Become manavao's partner",
            "Advertise on manavao.com",


        ];
        $data['fr'] = [
            "Développer votre réseau d'affaires",
            "Trouver des clients, des fournisseurs ou des partenaires",
            "Promouvoir votre organisation (ou votre territoire)",
            "Assurer une veille économique",
            "Devenir partenaire de manavao.com",
            "Annoncer sur manavao.com",


        ];
        $this->fillOption(InterestedIn::class, $this->arrayMix($data), $manager);
        
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            'Entrepreneurial project assistance',
            'Establishment support',
            'Administrative support',
            'Investment / financing support',
            'Technical cooperation / join development',
            'European projects',
            'Research cooperation',
            'Sales / distribution partners',
            'Franchise',
            'Legal advice',
            'Training ',
            'Facilities',
            'Quote request',
            'Call for tenders (public organisation) ',
            'Market survey',
            'Other',
        ];
        $data['fr'] = [
            "Assistance à la création d'entreprise",
            "Implantation ",
            "Assistance administrative",
            "Recherche de financements ",
            "Coopération technique ",
            "Projets européens",
            "Coopération R&D",
            "Partenaires commerciaux & distribution",
            "Franchise",
            "Conseil juridique ",
            "Formation professionnelle et coaching",
            "Locaux & installations",
            "Demande de devis",
            "Marché public",
            "Etude de marché & enquête",
            "Autres",
        ];
        $this->fillOption(ProjectType::class, $this->arrayMix($data), $manager);
         
        
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            "Corporate information",
            "Appointment & Recruitment",
            "Business information",
            "New product (or service) launching",
            "Awards & certifications",
            "Local establishment",
            "Corporate acquisition",
            "Partnership",
            "Networking information ",

        ];
        $data['fr'] = [
            "Information société",
            "Nomination & Recrutement",
            "Information clients",
            "Lancement de produits (ou services)",
            "Récompenses, prix, certifications",
            "Implantation ou filialisation",
            "Acquisition ",
            "Partenariats",
            "Réseaux ou clubs d'affaires",

        ];
        $this->fillOption(PostCategory::class, $this->arrayMix($data), $manager);
        
        
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            "Association",
            "Business club or network",
            "Economic development organisation",
            "Entrepreneur (not established))",
            "Financial organisation ",
            "International organisation",
            "Large company",
            "Incubator & business park",
            "Medias & websites",
            "Other economic stakeholder",
            "Professional Union",
            "Other public organisation",
            "SME",
            "Start-up",
            "Chamber of commerce & agriculture",
            "University & High school ",
            "European institution",
            "Local authority ",
            "Governement administration",
            "Non caritative organisation",
            "Investment fund",
            "Training organisation",
            "research center",
            "Technopole & innovation center",
            "Self employed & Auto-entrepreneurs",


        ];
        $data['fr'] = [
            "Association ",
            "Réseau & club d'affaires",
            "Agence ou service en charge du développement économique",
            "Société en création",
            "Institution financière & banque",
            "Organisation internationale",
            "Grande entreprise",
            "Incubateur & pépinière d'entreprises",
            "Médias & sites Internet",
            "Autre acteur économique",
            "Fédération professionnelle",
            "Autre organisme public",
            "Petite ou Moyenne entreprise",
            "Start-up",
            "Chambres de commerce, métiers ou agriculture",
            "Université & Ecoles supérieures",
            "Institution de l'Union européenne",
            "Collectivités territoriales",
            "Administration de l'Etat",
            "ONG",
            "Fonds d'investissement",
            "Organisme de formation ",
            "Centre de recherche & laboratoire scientifique",
            "Pôles technologiques et centres d'innovation",
            "Auto-entrepreneur",

        ];
        $this->fillOption(AuthorType::class, $this->arrayMix($data), $manager); 
        
        
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            "Accuracy",
            "Adaptable",
            "Advising",
            "Analytical",
            "Being Artistic/Creative",
            "Being Thorough",
            "Budgeting",
            "Business Storytelling",
            "Challenging Employees",
            "Coaching Individuals",
            "Collaboration",
            "Communication",
            "Conducting Meetings",
            "Conflict Resolution",
            "Confronting Others",
            "Creating Ideas",
            "Creating Innovation",
            "Creating New Solutions",
            "Creating New Procedures",
            "Creative Thinking",
            "Critical Thinking",
            "Customer Service",
            "Decision Making",
            "Defining Performance Standards",
            "Defining Problems",
            "Demonstrations",
            "Detail Management",
            "Dispensing Information",
            "Displaying Ideas",
            "Emotional Control",
            "Encouragement",
            "Evaluating",
            "Execution",
            "Financial Report Auditing",
            "Goal Setting",
            "Handling Complaints",
            "Human Resources",
            "Independent Action",
            "Information Search",
            "Investigation",
            "Involvement",
            "Knowledge ",
            "Language Translation",
            "Leadership",
            "Learning",
            "Listening",
            "Logical Thinking",
            "Follow-up",
            "Management",
            "Managing Finances",
            "Measuring Boundaries",
            "Meeting Deadlines",
            "Motivation",
            "Multicultural",
            "Negotiation",
            "Networking",
            "Non verbal Communication",
            "Numerical Analysis",
            "Oration",
            "Organisation performance",
            "Organisational Management",
            "Organisational Tasks",
            "Overseeing Meetings",
            "Overseeing Operation",
            "Personal Interaction",
            "Plan Development",
            "Planning",
            "Prediction",
            "Preparing Written Documents",
            "Prioritizing",
            "Problem Solving",
            "Proposal Writing",
            "Publications",
            "Public Relations",
            "Public Speaking",
            "Quality",
            "Questioning Others",
            "Reading Volumes",
            "Reasoning",
            "Recommendations",
            "Regulating Rules",
            "Rehabilitating Others",
            "Remembering Facts",
            "Reporting",
            "Responsibility",
            "Rigorous",
            "Scheduling",
            "Sketching",
            "Supervision",
            "Technical Support",
            "Team Building",
            "Teamwork",
            "Time Management",
            "Toleration",
            "Training",
            "Transferable",
            "Updating ",
            "Value",
        ];
        $data['fr'] = [
            "Précision",
            "Capacité d'adaptation",
            "Conseil",
            "Analyse",
            "Créativité ",
            "Etre minutieux",
            "Budget",
            "Capacité à raconter",
            "Challenge",
            "Coaching",
            "Collaboration",
            "Commubnication",
            "Conduite de réunions",
            "Résolution de conflits",
            "Faire se confronter les hommes ou les idées",
            "Apporter des idées",
            "Etre innovant",
            "Apporter de nouvelles solutions",
            "Imaginer de nouvelles procédures",
            "Esprit créatif",
            "Esprit critique",
            "Relation client",
            "Prise de décision",
            "Objectif de performance",
            "Identifier les problèmes",
            "Expliquer ",
            "Entrer dans les détails",
            "Diffuser l'information",
            "Visualiser des idées",
            "Contrôle émotionnel",
            "Capacité de motivation",
            "Evaluation",
            "Exécution",
            "Reporting financier",
            "Définition des objectifs",
            "Prendre en compte les réclamations",
            "Gestion des ressources humaines",
            "Indépendance d'action",
            "Veille ",
            "Capacité d'investigation",
            "Implication",
            "Connaissance",
            "Traduction et adaptation",
            "Leadership",
            "Apprendre des autres",
            "Ecoute des autres",
            "Esprit logique",
            "Suivi ",
            "Management",
            "Gestion de budget",
            "Délimitation des limites",
            "Respect des échéances",
            "Motivation",
            "Environnement multi-culturel",
            "Capacité de négociation",
            "Travail en réseau",
            "Communication non verbale",
            "Analyse de données",
            "Prise de parole en public",
            "Performance des organisations",
            "Management des organisations",
            "Gestion multi-tâches",
            " Compte-rendu de réunions",
            "Compte-rendu d'opérations",
            "Interactions ",
            "Plan de développement ",
            "Planification",
            "Anticipation",
            "Préparation de documents écrits",
            "Priorisation",
            "Résolution de problèmes",
            "Proposition écrite",
            "Rédaction",
            "Relations publiques et communication",
            "Parler en public",
            "Qualité",
            "Faire participer ",
            "Capacité de lecture",
            "Capacité de raisonnement",
            "Capacité de proposition",
            "Faire appliquer des règles",
            "Réimpliquer des personnes",
            "Se rappeler des faits",
            "Reporting",
            "Sesn des responsabilités",
            "Rigueur",
            "Programmer",
            "Mettre en scène",
            "Supervision",
            "Soutien technique",
            "Esprit d'équipe",
            "Travail en équipe",
            "Gestion du temps",
            "Tolérance",
            "Formation",
            "Transférabilité",
            "Mise à jour",
            "Création de valeur ",


        ];
        $this->fillOption(Skill::class, $this->arrayMix($data), $manager);
        $data = ['en' => [], 'fr' => []];
        $data['en'] = [
            "Congress",
            "Workshop",
            "Symposium",
            "Conference",
            "Professional exhibition",
            "Networking event",
            "Business breakfast",
            "Training session",
            "New product (or service)",
            "Press conference",

        ];
        $data['fr'] = [
            "Congrès",
            "Séminaire",
            "Symposium",
            "Conférence",
            "Salon professionnel",
            "Rencontre réseaux ou clubs d'affaires",
            "Petit-déjeuner d'affaires",
            "Formation professionnelle et coaching",
            "Lancement de produits (ou services)",
            "Conférence de presse",

        ];
        $this->fillOption(EventType::class, $this->arrayMix($data), $manager);
        */
        
        $data = ['en' => [], 'fr' => [], 'es' => [], 'ca' => []];
        $data['en'] = [
            "Local",
            "Regional",
            "National ",
            "Continental",
            "Global",
        ];
        $data['fr'] = [
            "Ville",
            "Région",
            "Pays",
            "Continent",
            "Global",
        ];
        $data['es'] = [
            "Local",
            "Regional",
            "Nacional ",
            "Continental",
            "Global",
        ];
        $data['ca'] = [
            "Local",
            "Regional",
            "Nacional ",
            "Continental",
            "Global",
        ];
        $this->fillOption(BusinessArea::class, $this->arrayMix($data), $manager);
        
        $data = ['en' => [], 'fr' => [], 'es' => [], 'ca' => []];
        $data['en'] = [
            "Català",
            "English",
            "Castellano",
            "French ",

        ];
        $data['fr'] = [
            "Catalan",
            "Anglais",
            "Castillan",
            "Français",

        ];
        $data['es'] = [
            "Catalán",
            "Inglés",
            "Castellano",
            "Francés",

        ];
        $data['ca'] = [
            "català",
            "Anglès",
            "castellà",
            "Francès",
        ];
        $this->fillOption(Language::class, $this->arrayMix($data), $manager);
        
        $data = ['en' => [], 'fr' => [], 'es' => [], 'ca' => []];
        $data['en'] = [
            "Self-employed",
            "1-10",
            "11-50",
            "51-250",
            "251-1000",
            "1001- 10,000",
            "10,000+",

        ];
        $data['fr'] = [
            "Indépendant",
            "1-10",
            "11-50",
            "51-250",
            "251-1000",
            "1001- 10,000",
            "10,000+",
        ];
        $data['es'] = [
            "Autónomo",
            "1-10",
            "11-50",
            "51-250",
            "251-1000",
            "1001- 10,000",
            "10,000+",
        ];
        $data['ca'] = [
            "Autónom",
            "1-10",
            "11-50",
            "51-250",
            "251-1000",
            "1001- 10,000",
            "10,000+",
        ];
        $this->fillOption(OrganisationSize::class, $this->arrayMix($data), $manager);
        
        $data = ['en' => [], 'fr' => [], 'es' => [], 'ca' => []];
        $data['en'] = [
            "Accounting",
            "Administrative",
            "Arts and Design",
            "Audit",
            "Business Development",
            "Cabinet",
            "Community life and social Services",
            "Consulting",
            "Customer service",
            "Economic development",
            "Education",
            "Engineering",
            "Entrepreneurship",
            "Environment and sustainable development",
            "Export department / export team / export sales department",
            "Finances",
            "Healthcare Services",
            "Human Resources",
            "IT department",
            "Legal",
            "Logistics",
            "Manufacturing department / production department",
            "Marketing",
            "Media and Communication",
            "Military and Protective Services",
            "Operations",
            "Organisation performance",
            "Program and Project Management",
            "Public relations team / public relations department",
            "Public procurement",
            "Purchasing",
            "Quality",
            "Real Estate",
            "Research and development team",
            "Sales",
            "Shipping department / dispatch department",
            "Supply chain",
            "Technical support team",
            "Transportation and public works",
            "Urban development",
            "Warehousing department",
        ];
        $data['fr'] = [
            "Comptabilité",
            "Gestion administrative",
            "Arts et design",
            "Audit",
            "Développement commercial",
            "Cabinet",
            "Vie citoyenne et services sociaux",
            "Communication",
            "Conseil",
            "Relation client",
            "Développement économique",
            "Education",
            "Ingéniérie",
            "Incubation & soutien start up",
            "Environnement et développement durable",
            "Export & international",
            "Finances",
            "Santé",
            "Ressources humaines",
            "Systèmes d'information",
            "Juridique",
            "Logistique et chaîne d’approvisionnement",
            "Production",
            "Marketing et publicité",
            "Media et communication",
            "Sécurité et protection",
            "Opérations & développement",
            "Performance",
            "Gestion de projets",
            "Relations publiques",
            "Marchés publics",
            "Achats",
            "Qualité",
            "Immobilier",
            "Recherche et développement",
            "Ventes",
            "Transports maritimes",
            "Chaîne d'approvisionnement",
            "Soutien",
            "Transports publics",
            "Aménagement du territoire & développement urbain",
            "Dépôts & entrepôts",

        ];
        $data['es'] = [
            "Contabilidad",
            "Administrativo",
            "Artes y diseño",
            "Auditoría",
            "Desarrollo de negocios",
            "Gabinete",
            "Comunidad y servicios sociales",
            "Comunicación",
            "Consultas",
            "Servicio al cliente",
            "Desarrollo económico",
            "Educación",
            "Ingeniería",
            "Emprendimiento",
            "Medio ambiente y desarrollo sostenible",
            "Depatamento de exportación/Equipo de exportación/Departamento de exportación y ventas",
            "Finanzas",
            "Servicio de atención médica",
            "Recursos humanos",
            "Servicio informático",
            "Jurídico",
            "Logística",
            "Departamento de producción",
            "Marketing",
            "Media y comunicación",
            "Seguridad y protección",
            "Operaciones y desarrollo",
            "Ejecución",
            "Gestión de programas y proyectos",
            "Equipo de relaciones públicas/Departamento de relaciones públicas",
            "Contratación pública",
            "Compras",
            "Calidad",
            "Bienes inmuebles",
            "Equipo de investigación y desarrollo",
            "Ventas",
            "Departamento de envío/Expedición de productos",
            "Cadena de suministro",
            "Equipo de soporte técnico",
            "Transporte y obras públicas",
            "Desarrollo urbano",
            "Depósito y almacén",

        ];
        $data['ca'] = [
            "Comptabilitat",
            "Administratiu",
            "Arts i disseny",
            "auditoria",
            "Desenvolupament de negocis",
            "Gabinet",
            "Comunitat i serveis socials",
            "comunicació",
            "consultes",
            "Servei al client",
            "desenvolupament econòmic",
            "educació",
            "Enginyeria",
            "emprenedoria",
            "Medi ambient i desenvolupament sostenible",
            "Depatamento d'exportació / Equip d'exportació / Departament d'exportació i vendes",
            "Finances",
            "Servei d'atenció mèdica",
            "recursos humans",
            "Servei informàtic",
            "Jurídic",
            "logística",
            "Departament de producció",
            "màrqueting",
            "Mitjana i comunicació",
            "Seguretat i protecció",
            "Operacions i desenvolupament",
            "execució",
            "Gestió de programes i projectes",
            "Equip de relacions públiques / Departament de relacions públiques",
            "contractació pública",
            "compres",
            "qualitat",
            "béns immobles",
            "Equip d'investigació i desenvolupament",
            "vendes",
            "Departament d'enviament / Expedició de productes",
            "Cadena de subministrament",
            "Equip de suport tècnic",
            "Transport i obres públiques",
            "desenvolupament urbà",
            "Dipòsit i magatzem",

        ];
        $this->fillOption(Department::class, $this->arrayMix($data), $manager);
        
        $data = ['en' => [], 'fr' => [], 'es' => [], 'ca' => []];
        $data['en'] = [
            "Self employed & Auto-entrepreneurs",
            "Craftsmen & merchants",
            "Small companies",
            "Mid-sized companies",
            "Large companies",
            "Public organisations",
            "Other",

        ];
        $data['fr'] = [
            "Indépendant & Auto-entrepreneur",
            "Artisans & Commerçants",
            "Petites entreprises",
            "Entreprises de taille intermédiaire",
            "Grandes entreprises",
            "Organismes publics",
            "Autres",

        ];
        $data['es'] = [
            "Trabajadores por cuenta propia y autónomos",
            "Artesanos y comerciantes",
            "Pequeñas empresas",
            "Empresas medianas",
            "Grandes compañías",
            "Organizaciones Públicas",
            "Otro",

        ];
        $data['ca'] = [
            "Treballadors per compte propi i autònoms",
            "Artesans i comerciants",
            "petites empreses",
            "empreses mitjanes",
            "grans companyies",
            "organitzacions Públiques",
            "Un altre",

        ];
        $this->fillOption(Clients::class, $this->arrayMix($data), $manager);
        
        $manager->flush();
    }

    private function fillOption($class, $data, $manager)
    {
        $this->removeAll($class, $manager);
        
        foreach ($data as $name) {
            $item = new $class;
            foreach ($name as $locale => $value) {
                $item->translate($locale)->setName($value);
            }
            $item->mergeNewTranslations();
            $manager->persist($item);
        }
    }
    
    private function removeAll($class, $em)
    {
        $collection = $em->getRepository($class)->findAll();
        foreach ($collection as $item){
            $em->remove($item);
        }
        $em->flush();
    }


    private function arrayMix($array)
    {
        $result = [];  
        foreach ($array as $locale => $arr)
        {       
            foreach ($arr as $key => $value) {
                $result[$key][$locale] = $value;
            }
        }
        return $result;
    }
}