<?php

namespace Bundles\OptionBundle\Repository;

/**
 * AuthorTypeTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorTypeTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
