<?php

namespace Bundles\OptionBundle\Repository;

/**
 * AuthorTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthorTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
