<?php

namespace Bundles\OptionBundle\Repository;

/**
 * EventTypeTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventTypeTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
