<?php

namespace Bundles\OptionBundle\Repository;

/**
 * PostCategoryTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostCategoryTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
