<?php

namespace Bundles\OptionBundle\Repository;

/**
 * ProjectTypeTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjectTypeTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
