<?php

namespace Bundles\OptionBundle\Repository;

/**
 * SkillTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
