<?php

namespace Bundles\OptionBundle\Repository;

/**
 * StaticPageTranslationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaticPageTranslationRepository extends \Doctrine\ORM\EntityRepository
{
}
