Bundles\UserBundle\Entity\User:
    type:  entity
    table: fos_user
    repositoryClass: Bundles\UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        firstName:
            type: string
            length: 255
            nullable: true
        lastName:
            type: string
            length: 255
            nullable: true
        city:
            type: string
            length: 255
        job:
            type: string
            length: '1024'
            nullable: true
        lat:
            type: decimal
            precision: 20
            scale: 14
        lng:
            type: decimal
            precision: 20
            scale: 14
        createdAt:
            type: datetime
        linkedIn:
            type: string
            length: 255
            nullable: true
        address:
            type: string
            length: 255
            nullable: true
        phone:
            type: string
            length: 255
            nullable: true            
        IM:
            type: string
            length: 255
            nullable: true
    oneToMany:
        sharedPosts:
            targetEntity: Bundles\StoreBundle\Entity\SharePost
            mappedBy: user
            cascade: ["remove"]
        likePosts:
            targetEntity: Bundles\StoreBundle\Entity\LikePost
            mappedBy: user
            cascade: ["remove"]
        posts:
            targetEntity: Bundles\StoreBundle\Entity\Post
            mappedBy: author
            cascade: ["remove"]
        friendUsers:
            targetEntity: Bundles\StoreBundle\Entity\Friend
            mappedBy: user
            cascade: ["remove"]
        friends:
            targetEntity: Bundles\StoreBundle\Entity\Friend
            mappedBy: friend
            cascade: ["remove"]
    manyToMany:
        communities:
            targetEntity: Bundles\StoreBundle\Entity\Community
            inversedBy: users
            joinTable:
                onDelete: CASCADE
                name: user_to_community
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    community_id:
                        referencedColumnName: id
        interestedIn:
            targetEntity: Bundles\OptionBundle\Entity\InterestedIn
            joinTable:
                onDelete: CASCADE
                name: user_to_interested_in
                joinColumns:
                    user_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    interested_in_id:
                        referencedColumnName: id    
    oneToOne:
        image:
            targetEntity: Bundles\ImageBundle\Entity\Image
            cascade: ["remove"]
            joinColumn:
                name: image_id
                referencedColumnName: id
        inform:
            targetEntity: Info
            cascade: ["remove"]
            joinColumn:
                name: inform_id
                referencedColumnName: id
    manyToOne:
        industry:
            targetEntity: Bundles\OptionBundle\Entity\Industry
            joinColumn:
                name: industry_id
                referencedColumnName: id
        country:
            targetEntity: Bundles\StoreBundle\Entity\Country
            joinColumn:
                name: country_id
                referencedColumnName: id
        urbanArea:
            targetEntity: Bundles\StoreBundle\Entity\UrbanArea
            joinColumn:
                name: urban_area_id
                referencedColumnName: id
        category:
            targetEntity: Bundles\OptionBundle\Entity\Category
            joinColumn:
                name: category_id
                referencedColumnName: id
        zone:
            targetEntity: Bundles\OptionBundle\Entity\Zone
            joinColumn:
                name: zone_id
                referencedColumnName: id
        type:
            targetEntity: Bundles\OptionBundle\Entity\AuthorType
            joinColumn:
                name: type_id
                referencedColumnName: id
            
