<?php

namespace Bundles\StoreBundle\Repository;

/**
 * CityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getArray($areaId)
    {
        $qb = $this->createQueryBuilder('c')
            ->select('c.id, c.name')
            ->where('c.urbanArea = '.$areaId)
//            ->orderBy('c.name', 'ASC')
            ->getQuery()
        ;
        
        return $qb->getArrayResult();
    }
}
