<?php

namespace Bundles\StoreBundle\Repository;

/**
 * EventPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventPostRepository extends \Doctrine\ORM\EntityRepository
{
}
