<?php

namespace Bundles\StoreBundle\Repository;
use Bundles\StoreBundle\Entity\Post;
use Bundles\UserBundle\Entity\User;

/**
 * LikePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikePostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLikePost(User $user, Post $post)
    {
        return $this->createQueryBuilder('lPost')
                ->where('lPost.user = :user')
                ->setParameter(':user', $user)
                ->andWhere('lPost.post = :post')
                ->setParameter(':post', $post)
                ->getQuery()
                ->getOneOrNullResult();
    }
}
