<?php

namespace Bundles\StoreBundle\Repository;

/**
 * OpportunityPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OpportunityPostRepository extends \Doctrine\ORM\EntityRepository
{
}
