<?php

namespace Bundles\StoreBundle\Repository;
use Bundles\UserBundle\Entity\User;
use Bundles\StoreBundle\Entity\Community;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserWallPost(User $user, $type)
    {
//        dump($user); die;
        $qb = $this->createQueryBuilder('post')
                ->leftJoin('post.sharedUsers', 'shu')
                ->where('post.author = :user')
                ->orWhere('shu.user = :user')
                ->setParameter('user', $user); 
        if ($type) {
            $qb->andWhere('post.type = :type')
                ->setParameter('type', $type);
        }
        $posts = $qb->getQuery()->getResult();
//        dump($posts); die;
        foreach ($posts as $post) {
            if ($post->getAuthor() == $user) {
                $post->showDate = $post->getCreatedAt();
            } else {
                $date = $this->createQueryBuilder('post')
                        ->leftJoin('post.sharedUsers', 'shu')
                        ->select('shu.createdAt as showDate')
                        ->where('shu.user = :user')
                        ->setParameter('user', $user)
                        ->andWhere('shu.post = :post')
                        ->setParameter('post', $post)
                        ->getQuery()
                        ->getSingleResult();
                $post->showDate = $date['showDate'];
            }          
        }
        $returnPosts = $this->bubbleSort($posts);
        return $returnPosts;
        
    }
    
    public function getNewsPost($comm, $type, $user = null)
    {
        $qb = $this->createQueryBuilder('post')
                ->join('post.communities', 'comm')
                ->where('comm.id IN (:comm)')
                ->setParameter('comm', $comm);
//                ->leftJoin('post.sharedUsers', 'shu');
//                ->where('post.author = :user')
//                ->orWhere('shu.user = :user')
//                ->setParameter('user', $user); 
        if ($type) {
            $qb->andWhere('post.type = :type')
                ->setParameter('type', $type);
        }
        if ($user) {
            $qb->andWhere('post.author != :user')
                ->setParameter('user', $user);
        }
        $posts = $qb->orderBy('post.createdAt', 'DESC')->getQuery()->getResult();
        foreach ($posts as $post) {
            $post->showDate = $post->getCreatedAt();
        }
        return $posts;
        
    }
    
    public function getFriendsPosts($friends, $type = null)
    {
        $qb = $this->createQueryBuilder('post')
                ->where('post.author IN (:friends)')
                ->setParameter('friends', $friends); 
        if ($type) {
            $qb->where('post.type = :type')
                ->setParameter('type', $type);
        }
        $posts = $qb->orderBy('post.createdAt', 'DESC')->getQuery()->getResult();
        return $posts;
    }
    
    public function getCommunityPost(Community $comm, $type = null)
    {
        $qb = $this->createQueryBuilder('post')
                ->where(':comm MEMBER OF post.communities')
                ->setParameter('comm', $comm);
        if ($type) {
            $qb->andWhere('post.type = :type')
                ->setParameter('type', $type);
        }
        return $qb->orderBy('post.createdAt', 'DESC')
                ->getQuery()
                ->getResult();
    }
    
    public function getLasWeekCommunityPost(Community $comm, $from, $to, $type)
    {
        return $this->createQueryBuilder('post')
                ->where(':comm MEMBER OF post.communities')
                ->setParameter('comm', $comm)
                ->andWhere('post.type = :type')
                ->setParameter('type', $type)
                ->andWhere('post.createdAt BETWEEN :from AND :to')
                ->setParameter('from', $from)
                ->setParameter('to', $to)
                ->orderBy('post.createdAt', 'DESC')
                ->getQuery()
                ->getResult();
    }
    
    private function bubbleSort($array) {
        $count = count($array);
        for ($i = $count-1; $i >= 0; $i--) {
            for ($j = 0; $j < $i; $j++ ) {
                if ($array[$j]->showDate < $array[$j+1]->showDate) {
                    $temp = $array[$j];
                    $array[$j] = $array[$j+1];
                    $array[$j+1] = $temp;
                }
            }
        }
        return $array;
    }
}
