<?php

namespace Bundles\StoreBundle\Repository;
 use Bundles\StoreBundle\Entity\Post;
 use Bundles\UserBundle\Entity\User;

/**
 * SharePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SharePostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSharedPost(User $user, Post $post)
    {
        return $this->createQueryBuilder('shPost')
                ->where('shPost.user = :user')
                ->setParameter(':user', $user)
                ->andWhere('shPost.post = :post')
                ->setParameter(':post', $post)
                ->getQuery()
                ->getOneOrNullResult();
    }
}
