<?php

namespace Bundles\StoreBundle\Repository;

/**
 * UpdatePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UpdatePostRepository extends \Doctrine\ORM\EntityRepository
{
}
